# volumes:
#   local_postgres_data: {}
#   local_postgres_data_backups: {}

services:
  local-app:
    build:
      context: ../.. # Points to root of project
      dockerfile: ./compose/local/app/Dockerfile
      target: development
    image: local_app
    container_name: local_app
    # Uncomment the following line to enable the PostgreSQL service
    # depends_on:
    #   - postgres
    volumes:
      - ../../:/app:z
    env_file:
      - ../../.envs/.local/.app
      - ../../.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  anki-desktop:
    image: "pnorcross/anki-desktop:latest"
    volumes:
      - ../../app/data/anki/config:/config/app
    ports:
      - 3000:3000
      # Anki Connect port
      - 8765:8765
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
